### ISSUE TITLE
Missing Rails icon

### ISSUE THREAD

**Issue by yuaanlin** [zeabur/service-icons#1]
https://rubyonrails.org/
![Screenshot 2023-02-19 at 10 42 47 PM](https://user-images.githubusercontent.com/21105863/219955328-30400552-e859-474d-903f-5ca5676b6704.png)

**Comment by MichaelYuhe** [comment]
<img width="449" alt="image" src="https://user-images.githubusercontent.com/63531512/220003701-4b275c54-fa5b-457a-a7cd-eff91343dd36.png">
Rails icon added.
