### ISSUE TITLE
Missing Deno and Fresh icon

### ISSUE THREAD

**Issue by yuaanlin** [zeabur/service-icons#2]
https://deno.land/
https://fresh.deno.dev/
![Screenshot 2023-02-19 at 10 44 22 PM](https://user-images.githubusercontent.com/21105863/219955401-e053d7cc-fba4-47ac-926e-6d39b65b074a.png)

**Comment by MichaelYuhe** [comment]
<img width="602" alt="image" src="https://user-images.githubusercontent.com/63531512/220004757-97453114-89c2-4447-a4e9-08b08bacd672.png">
Thanks for feedback. Deno and Fresh icons now are added.
